spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/file_manager?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

okta:
  oauth2:
    issuer: https://dev-407428.okta.com/oauth2/default
    clientId: 0oa23n7y05iGGONxy357
#    client-secret: 8uE0lL-sM2ShTBrax6bD9knGLCyPpPYN_EHRk3J6

server:
  port: 8080
