spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_manager?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
okta:
  oauth2:
    issuer: https://{replace-me}/oauth2/default
    clientId: {replace-me}
