spring:
  datasource:
    url: jdbc:mysql://localhost:8889/file_manager?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 5MB
      # Max Request Size
      max-request-size: 10MB

okta:
  oauth2:
    issuer: https://{replace-me}/oauth2/default
    clientId: {replace-me}


